#!/bin/sh

. "$SNAP/bin/snap-utils.sh"

enforce_gog_symlink

if [ $? = 1 ]; then
    UNINST_EXE=""
    if [ -e "$SNAP_USER_COMMON/.wine/drive_c/Program Files (x86)/GOG Galaxy/unins000.exe" ]; then
        UNINST_EXE="$SNAP_USER_COMMON/.wine/drive_c/Program Files (x86)/GOG Galaxy/unins000.exe"
    elif [ -e "$SNAP_USER_COMMON/.wine/drive_c/Program Files/GOG Galaxy/unins000.exe" ]; then
        UNINST_EXE="$SNAP_USER_COMMON/.wine/drive_c/Program Files/GOG Galaxy/unins000.exe"
    fi

    if [ -n "$UNINST_EXE" ]; then
        "${WINELOADER}" "${UNINST_EXE}" /silent
        exec "$0" "$@"
    fi
fi

# todo remove again when dxvk works
# $SNAP/dxvk/setup_dxvk.sh uninstall

# "${WINELOADER}" "$WINEPREFIX/drive_c/ProgramData/GOG.com/Galaxy/redists/GalaxyCommunication.exe" &
# sleep 2
