#!/bin/sh

. "$SNAP/bin/snap-utils.sh"

enforce_gog_symlink

if [ $? = 1 ] && [ -e "$SNAP_USER_COMMON/.wine/drive_c/Program Files (x86)/GOG Galaxy/unins000.exe" ]; then
    env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINEPREFIX}/drive_c/Program Files (x86)/GOG Galaxy/unins000.exe" /silent
    exec "$0" "$@"
fi

env WINEARCH="${WINEARCH}" WINEPREFIX="${WINEPREFIX}" "${WINELOADER}" "${WINEPREFIX}/drive_c/ProgramData/GOG.com/Galaxy/redists/GalaxyCommunication.exe"
