name: gog-galaxy-wine
icon: snap/gui/gog-galaxy.png
summary: GOG Galaxy
version: '2.0'
description: >
  The gaming Client designed for a convenient purchasing, playing and updating
  games, as well as an online play between gaming platforms, GOG Galaxy is also
  built with optionality in mind, and a belief that you should own the games you
  buy.

  This is the Windows version running via WINE. It is experimental. Some games
  may not work correctly, or at all. Your mileage may vary.

  Some games might require you to run
  `snap connect gog-galaxy-wine:hardware-observe`, and/or
  `snap connect gog-galaxy-wine:process-control` in a terminal (or use the
  Software Centre in Ubuntu 18.04 to toggle "Access to hardware information"
  and/or "Pause ro end any process on the system") to grant extra permissions
  for the application. Though all the games tested so far do not need these
  permissions.
grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
  - build-on: i386

layout:
  /usr/share/libdrm:
    bind: $SNAP/usr/share/libdrm

plugs:
  wine-runtime:
    interface: content
    target: $SNAP/wine-runtime
    default-provider: wine-platform-runtime
  wine-6-stable:
    interface: content
    target: $SNAP/wine-platform
    default-provider: wine-platform-6-staging

environment:
  TRICKS: "corefonts"
  WINEDLLOVERRIDES: mshtml=
  SYSTEM_WGETRC: $SNAP/etc/wgetrc
  # LC_ALL: "C.UTF-8"
  # SNAP_TITLE: "$SNAPCRAFT_PROJECT_SUMMARY"
  # SNAP_ICON: "$SNAP/usr/share/icons/gog-galaxy.png"
  # SNAP_SUPPORT_URL: "https://github.com/diddlesnaps/gog-galaxy-wine/issues"

apps:
  gog-galaxy-wine:
    extensions: [gnome-3-28]
    command: bin/sommelier run-exe
    environment:
      RUN_EXE: C:/Program Files (x86)/GOG Galaxy/GalaxyClient.exe
      INSTALL_URL: https://webinstallers.gog.com/download/GOG_Galaxy_2.0.exe
      # INSTALL_FLAGS: /silent
    plugs:
      - audio-playback
      - audio-record
      - bluez
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - network-observe
      - opengl
      - process-control
      - removable-media
      - screen-inhibit-control

  wine:
    extensions: [gnome-3-28]
    command: bin/sommelier
    plugs:
      - home
      - network

  winetricks:
    extensions: [gnome-3-28]
    command: bin/sommelier winetricks
    plugs:
      - home
      - network

parts:
  sommelier-core:
    plugin: make
    source: https://github.com/snapcrafters/sommelier-core.git
    source-branch: "1.0"
