name: gog-galaxy-wine
version: latest
version-script: |
  cat $SNAPCRAFT_STAGE/version
summary: GOG Galaxy
description: |
 GOG Galaxy
 .
 run `snap connect gog-galaxy-wine:hardware-observe`, and
     `snap connect gog-galaxy-wine:process-control`.

grade: stable
confinement: strict
architectures:
  - build-on: amd64
  - build-on: i386

apps:
  gog-galaxy-wine:
    command: env INSTALL_URL="https://content-system.gog.com/open_link/download?path=/open/galaxy/client/setup_galaxy_$(cat $SNAP/version).exe"
      $SNAP/bin/sommelier "$WINEPREFIX/drive_c/Program Files/GOG Galaxy/GalaxyClient.exe" /runWithoutUpdating
    environment:
      TRICKS: "corefonts vcrun2015 d3dx11_43"
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio
      - wayland
      - x11
  communication:
    command: bin/sommelier "$WINEPREFIX/drive_c/users/Public/GOG.com/Galaxy/redists/GalaxyCommunication.exe"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - hardware-observe
      - home
      - joystick
      - network
      - network-bind
      - opengl
      - process-control
      - pulseaudio
      - wayland
      - x11
  wineboot:
    command: bin/sommelier $SNAP/bin/wineboot
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
  winecfg:
    command: bin/sommelier $SNAP/bin/winecfg
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
    plugs:
      - desktop
      - desktop-legacy
      - pulseaudio
      - wayland
      - x11
  winetricks:
    command: bin/sommelier $SNAP/bin/winetricks prefix="$WINEPREFIX"
    environment:
      WINEPREFIX: "$SNAP_USER_COMMON/.wine"
      LC_ALL: "C.UTF-8"
    plugs:
      - desktop
      - desktop-legacy
      - network
      - pulseaudio
      - wayland
      - x11

parts:
  enable-i386:
    plugin: nil
    build-attributes:
      - no-system-libraries
    override-build: |
      snapcraftctl build
      if [ "$SNAPCRAFT_ARCH_TRIPLET" = "x86_64-linux-gnu" ]; then
        dpkg --add-architecture i386
        apt update
      fi

  wine:
    plugin: nil
    build-attributes:
      - no-system-libraries
    build-packages:
      - wget
    override-build: |
      snapcraftctl build

      # wget and dpkg extract the wine debs
      ## supporting binaries which are arch-specific but the same filenames in both architectures so we only install the native architecture
      DEB_URLS="https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-devel_3.9.0~xenial_${SNAP_ARCH}.deb"

      ## wine loaders - this one is the native system architecture
      DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-devel-${SNAP_ARCH}_3.9.0~xenial_${SNAP_ARCH}.deb"

      if [ "$SNAP_ARCH" = "amd64" ]; then
        ## on amd64 builds we need to also bundle the i386 wine loaders
        DEB_URLS="$DEB_URLS https://dl.winehq.org/wine-builds/ubuntu/pool/main/wine-devel-i386_3.9.0~xenial_i386.deb"
      fi

      for DEB_URL in ${DEB_URLS}; do
        DEB=$(basename "${DEB_URL}")
        echo "Downloading ${DEB_URL}..."
        wget --quiet "${DEB_URL}" -O "${SNAPCRAFT_PART_INSTALL}/${DEB}"
        echo "Unpacking ${DEB}..."
        dpkg -x "${SNAPCRAFT_PART_INSTALL}/${DEB}" ${SNAPCRAFT_PART_INSTALL}
        rm -f "${SNAPCRAFT_PART_INSTALL}/${DEB}"
      done

      # Organise and cleanup
      cp -a ${SNAPCRAFT_PART_INSTALL}/opt/wine-devel/* ${SNAPCRAFT_PART_INSTALL}/
      rm -rf ${SNAPCRAFT_PART_INSTALL}/opt
      rm -rf ${SNAPCRAFT_PART_INSTALL}/share/applications
      rm -rf ${SNAPCRAFT_PART_INSTALL}/share/man
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/doc
      rm -rf ${SNAPCRAFT_PART_INSTALL}/usr/share/lintian
    after:
      - enable-i386

  wine-runtime:
    plugin: nil
    build-attributes:
      - no-system-libraries
    stage-packages:
      ### Depends from wine-devel-${SNAP_ARCH}_3.9.0~xenial_${SNAP_ARCH}.deb debian/control
      - libasound2
      #- libc6
      - libglib2.0-0
      #- libgphoto2-6
      - libgstreamer-plugins-base1.0-0
      - liblcms2-2
      - libldap-2.4-2
      - libmpg123-0
      - libncurses5
      - libopenal1
      - libpcap0.8
      - libpulse0
      - libudev1
      - libxext6
      - libxml2
      - zlib1g
      ### Recommends from wine-devel-${SNAP_ARCH}_3.9.0~xenial_${SNAP_ARCH}.deb debian/control
      #- libcapi20-3
      #- libcups2
      - libdbus-1-3
      - libfontconfig1
      - libfreetype6
      - libglu1-mesa
      - libgnutls30
      - libgsm1
      - libgssapi-krb5-2
      - libjpeg8
      #- libodbc1
      - libosmesa6
      - libpng12-0
      #- libsane
      - libsdl2-2.0-0
      - libtiff5
      - libv4l-0
      - libvulkan1
      - libxcomposite1
      - libxcursor1
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libxslt1.1
      - libxxf86vm1
      # Required for authentication - Observed in Steam and Track Mania
      - winbind
      - samba-libs
      - on amd64:
        ### Depends from wine-devel-i386_3.9.0~xenial_i386.deb debian/control
        - libasound2:i386
        - libc6:i386
        - libglib2.0-0:i386
        #- libgphoto2-6:i386
        - libgstreamer-plugins-base1.0-0:i386
        - liblcms2-2:i386
        - libldap-2.4-2:i386
        - libmpg123-0:i386
        - libncurses5:i386
        - libopenal1:i386
        - libpcap0.8:i386
        - libpulse0:i386
        - libudev1:i386
        - libxext6:i386
        - libxml2:i386
        - zlib1g:i386
        ### Recommends from wine-devel-i386_3.9.0~xenial_i386.deb debian/control
        #- libcapi20-3:i386
        #- libcups2:i386
        - libdbus-1-3:i386
        - libfontconfig1:i386
        - libfreetype6:i386
        - libglu1-mesa:i386
        - libgnutls30:i386
        - libgsm1:i386
        - libgssapi-krb5-2:i386
        - libjpeg8:i386
        #- libodbc1:i386
        - libosmesa6:i386
        - libpng12-0:i386
        #- libsane:i386
        - libsdl2-2.0-0:i386
        - libtiff5:i386
        - libv4l-0:i386
        - libvulkan1:i386
        - libxcomposite1:i386
        - libxcursor1:i386
        - libxfixes3:i386
        - libxi6:i386
        - libxinerama1:i386
        - libxrandr2:i386
        - libxrender1:i386
        - libxslt1.1:i386
        - libxxf86vm1:i386
        # Required for authentication - Observed in Steam and Track Mania
        - winbind:i386
        - samba-libs:i386
    override-build: |
      snapcraftctl build
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/applications
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
    after:
      - enable-i386

  gog-galaxy:
    plugin: dump
    build-attributes:
      - no-system-libraries
    source: scripts
    organize:
      'sommelier': bin/
      'winetricks': bin/
      'zenity': bin/
    build-packages:
      - wget
    stage-packages:
      - cabextract         # winetricks
      - libgdk-pixbuf2.0-0 # yad
      - libgtk-3-0         # yad
      - libnotify4         # yad
      - perl-base          # winetricks
      - shared-mime-info
      - unzip              # winetricks
      - wget               # winetricks
      - yad                # winetricks
    override-build: |
      snapcraftctl build

      wget --quiet "https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks" -O $SNAPCRAFT_PART_INSTALL/winetricks
      chmod +x $SNAPCRAFT_PART_INSTALL/winetricks

      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/init.d
      rm -rf $SNAPCRAFT_PART_INSTALL/etc/logrotate.d
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/fc-*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/bin/gtk-*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/dconf/dconf-service
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/lib/glib-networking/glib-pacrunner
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/GConf
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/aclocal
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apport
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/apps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bash-completion
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/bug
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/debhelper
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/doc-base
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Adwaita
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/Humanity*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/LoginIcons
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/icons/ubuntu-mono*
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/info
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/kde4
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/lintian
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/man
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/perl5
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pixmaps
      rm -rf $SNAPCRAFT_PART_INSTALL/usr/share/pkgconfig
    after:
      - enable-i386

  gog-galaxy-version:
    plugin: nil
    override-build: |
      curl https://www.gog.com/galaxy | grep 'https://content-system.gog.com/open_link/download?path=/open/galaxy/client/setup_galaxy.*.exe' | head -n1 | sed -E -e 's|^.*"https://content-system\.gog\.com/open_link/download\?path=/open/galaxy/client/setup_galaxy_(.*)\.exe".*$|\1|' > $SNAPCRAFT_PART_INSTALL/version
